blog/urls.py
from django.urls import path, include
from blog.views import *
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('', inicio, name='inicio'),
    path('inicio', inicio, name='inicio'),
    path('pages', mostrarEntradas, name='pages'),
    path('login', loginRequest, name='login'),
    path('entrada/<entr_id>',mostrarEntrada, name='mostrarEntrada'),
    path('inicioUsuario', mostrarEntradasUsuario, name='inicioUsuario'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('registro', registrarUsuario, name='registrarUsuario'),
    path('editarperfil', editarPerfil, name='editarPerfil'),
    path('nuevaEntrada', nuevaEntrada, name='nuevaEntrada'),
    path('editarEntrada/<entr_id>', editarEntrada, name='editarEntrada'),
    path('eliminarEntrada/<entr_id>', eliminarEntrada, name='eliminarEntrada'),
    path('megusta/<entr_id>', likeEntrada, name='megusta'),   
    path('favoritos', entradasFavoritas, name='favoritos'),
    path('about', about, name='about') ,
]

blogRecetas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('blog.urls','blog'),namespace='blog')),
    path('mensajeria/', include(('mensajeria.urls', 'mensajeria'), namespace='mensajeria')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mensajeria/urls.py
from unicodedata import name
from django.urls import path
from mensajeria.views import *


urlpatterns = [
    path('nuevoMensaje', nuevoMensaje, name='nuevoMensaje'),
    path('bandejaEntrada', bandejaEntrada, name='bandejaEntrada'),
    path('eliminarMensaje/<id>', eliminarMensaje, name='eliminarMensaje'),
    path('responderMensaje/<id>', responderMensaje, name='responderMensaje'),
    path('mostrarMensaje/<id>', mostrarMensaje, name='mostrarMensaje'),
]

blogRecetas/templates/album/confirmarBorrado.html
{% extends 'album/index.html' %}
{% load static %}

{% block seccionCentral %}
<p class="lead text-muted">Está seguro que desea eliminar la receta: {{ entrada.titulo }}</p>
<a href="javascript:history.back()"class="btn btn-secondary my-2">Cancelar</a>
<form action="{% url 'blog:eliminarEntrada' entrada.id %}" method="post"> {% csrf_token %}
    <button type="submit" class="btn btn-danger my-2">Borrar</a>
</form>

{% endblock %}

{% block entradasBlock %}    
{% endblock %}

blogRecetas/templates/album/editarEntrada.html
{% extends 'album/index.html' %}
{% load static %}

{% block seccionCentral %}
<h1 class="fw-light">Editando {{ entrada.titulo }}</h1>
{% endblock %}

{% block entradasBlock %}
    {% if form %}
    <div class="shadow p-4 mb-5 bg-body rounded">
        <a href="javascript:history.back()" class="btn btn-sm btn-outline-primary">Volver</a>
    <form action="{% url 'blog:editarEntrada' entr_id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar cambios</button>          
    </form>
    </div>
    {% endif %}
    {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>          
        {% endfor %}
    {% endif %}
    {% if mensaje %}        
    <div class="alert alert-info" role="alert">
        {{ mensaje }}
    </div>                 
    {% endif %}
{% endblock %}

blogRecetas/templates/album/index.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Blog de Recetas</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album/">

    

    

<link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
  </head>
  <body>
    
<header>
  <!-- esta es la barra colapsada -->
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted"></p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white"></h4>
          <ul class="list-unstyled">
            <li><a href="/admin" class="text-white">Administrador</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'blog:inicioUsuario' %}" class="text-white">Mis Entradas</a></li>
            <li><a href="{% url 'blog:editarPerfil' %}" class="text-white">Editar Perfil ( {{ user.first_name }} {{ user.last_name }} )</a></li>
            <li><a href="{% url 'mensajeria:bandejaEntrada' %}" class="text-white">Mensajes</a></li>            
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!--esta es la barra sin colapsar -->
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'blog:inicio' %}" class="navbar-brand d-flex align-items-center">
        <img src="/media/icons/dieta.png" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></img>
        <strong>Recetas</strong>
      </a>      
      {% if not request.user.is_authenticated %}
      <a class="navbar-toggler" href="{% url 'blog:login' %}" style="align-self: right; align-items: right;position: absolute;top: 25%; left: 75%;">
        <strong>Login</strong>
      </a>
      {% endif %}
      {% if request.user.is_authenticated %}
      <a class="navbar-toggler" href="{% url 'blog:logout' %}?next={% url 'blog:inicio' %}" style="align-self: right; align-items: right;position: absolute;top: 25%; left: 75%;">
        <strong>Logout</strong>
      </a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>  
  </div>
</header>

<main>
  <!-- es la seccion central antes de las entradas -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        {% block seccionCentral %}
        {% endblock %}
      </div>
    </div>
  </section>

  <!-- aca van las entradas -->

  <div class="album py-5 bg-light">
    <div class="container">      
    {% block entradasBlock %}
    {% endblock %}
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-0"><a href="/">Volver a la página de inicio</a> o lee sobre <a href="{% url 'blog:about' %}">quienes somos</a>.</p>
  </div>
</footer>


    <script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>

blogRecetas/templates/album/inicioBlog.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Blog Recetas</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/blog/">

    

    

<link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    
<div class="container">
  <header class="blog-header lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="link-secondary" href="#"></a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="{% url 'blog:inicio' %}">Blog de Recetas</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <!-- <a class="link-secondary" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a> -->
        {% if request.user.is_authenticated %}
        <a class="btn btn-sm btn-outline-danger" href="{% url 'blog:logout' %}?next={% url 'blog:inicio' %}">Logout</a>
        {% else %}
        <a class="btn btn-sm btn-outline-primary" href="{% url 'blog:registrarUsuario' %}">Registrate</a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:login' %}">Login</a>
        {% endif %}
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 link-secondary" href="{% url 'blog:pages' %}">Todas las Recetas</a>
      <a class="p-2 link-secondary" href="{% url 'blog:nuevaEntrada' %}">Agregar Recetas</a>
      {% if request.user.is_authenticated %}
      <a class="p-2 link-secondary" href="{% url 'blog:inicioUsuario' %}">Mis Recetas</a>
      <a class="p-2 link-secondary" href="{% url 'blog:favoritos' %}">Favoritos</a>
      <a class="p-2 link-secondary" href="{% url 'mensajeria:bandejaEntrada' %}">Mensajes</a>
      <a class="p-2 link-secondary" href="{% url 'blog:editarPerfil' %}">Editar Perfil</a>
      {% endif %}
      <a class="p-2 link-secondary" href="/admin">Administrador</a>      
    </nav>
  </div>
</div>

<main class="container">
  {% if entrada1 %}
  <div class="p-4 p-md-5 mb-4 rounded text-bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">{{entrada1.titulo}}</h1>
      <p class="lead my-3">{{entrada1.subtitulo}}</p>
      <p class="lead mb-0"><a href="{% url 'blog:mostrarEntrada' entrada1.id %}" class="text-white fw-bold">Continuar leyendo...</a></p>
    </div>
  </div>
  {% endif %}  
  <div class="row mb-2">
    {% if entrada2 %}
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{entrada2.titulo}}</h3>
          <div class="mb-1 text-muted">{{entrada2.fecha}}</div>
          <p class="card-text mb-auto">{{entrada2.subtitulo}}</p>
          <a href="{% url 'blog:mostrarEntrada' entrada2.id %}" class="stretched-link">Continuar leyendo</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          {% if entrada2.imagen %}
          <img class="bd-placeholder-img" width="200" height="250" src="{{entrada2.imagen.url}}" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#55595c"/></img>
          {% else %}
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          {% endif %}          
        </div>
      </div>
    </div>
    {% endif %}
    {% if entrada3 %}
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{entrada3.titulo}}</h3>
          <div class="mb-1 text-muted">{{entrada3.fecha}}</div>
          <p class="mb-auto">{{entrada3.subtitulo}}</p>
          <a href="{% url 'blog:mostrarEntrada' entrada3.id %}" class="stretched-link">Continuar leyendo</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          {% if entrada3.imagen %}
          <img class="bd-placeholder-img" width="200" height="250" src="{{entrada3.imagen.url}}" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#55595c"/></img>
          {% else %}
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          {% endif %} 
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="row g-5">
    {% if entrada4 %}
    <div class="col-md-8">
      <article class="blog-post">
        <h2 class="blog-post-title mb-1">{{entrada4.titulo}}</h2>
        <p class="blog-post-meta">{{entrada4.fecha}} Autor: {{entrada4.autor}}</p>
        <img src="{{entrada4.imagen.url}}" width="400" height="350"></img>
        <p>{{entrada4.cuerpo|safe}}</p>
      
    </div>
    {% endif %}

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-light rounded">
          <h4 class="fst-italic">About</h4>
          <p class="mb-0">Blog donde vas a encontrar las mejores recetas, podes subir todas tus recetas favoritas y compartirlas con la comunidad<br>
            <a href="{% url 'blog:about' %}">Leer más...</a>
          </p>
        </div>
        <!--
        <div class="p-4">
          <h4 class="fst-italic">Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a href="#">March 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">January 2021</a></li>
            <li><a href="#">December 2020</a></li>
            <li><a href="#">November 2020</a></li>
            <li><a href="#">October 2020</a></li>
            <li><a href="#">September 2020</a></li>
            <li><a href="#">August 2020</a></li>
            <li><a href="#">July 2020</a></li>
            <li><a href="#">June 2020</a></li>
            <li><a href="#">May 2020</a></li>
            <li><a href="#">April 2020</a></li>
          </ol>
        </div>-->        
      </div>
    </div>
  </div>

</main>

<footer class="blog-footer">
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>


    
  </body>
</html>

blogRecetas/templates/album/inicioPublico.html
{% extends 'album/index.html' %}
{% load static %}
{% block seccionCentral %}
<h1 class="fw-light">Blog de Recetas</h1>
        <p class="lead text-muted">En nuestro blog de recetas vas a encontrar las mejores recetas de cocina.</p>
        {% if not request.user.is_authenticated %}
        <p>
          <a href="{% url 'blog:registrarUsuario' %}" class="btn btn-primary my-2">Registrate</a>
          <a href="{% url 'blog:login' %}" class="btn btn-secondary my-2">Iniciar Sesión</a>
        </p>
        {% endif %}
{% endblock %}
{% block entradasBlock %}
{% if entradas %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- debe ir un for para mostrar las entradas. Llegan por parametro como 'entradas'-->        
        {% for entry in entradas %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{entry.imagen.url}}" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#55595c"/></img>

            <div class="card-body">
              <p class="mb-0"><strong>{{entry.titulo}}</strong></p>
              <p class="card-text">{{ entry.subtitulo }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:mostrarEntrada' entry.id %}">View</a>
                  <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:megusta' entry.id %}">Me Gusta</a>
                  {% if request.user.is_authenticated %}
                    {% if entry.autor == request.user %}
                    <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:editarEntrada' entry.id %}">Edit</a>
                    <a type="button" class="btn btn-sm btn-outline-danger" href="{% url 'blog:eliminarEntrada' entry.id %}">Delete</a>
                    {% endif %}
                  {% endif %}
                </div>
                <small class="text-muted">Autor: {{ entry.autor }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}        
      </div> 
{% endif %}
{% endblock %}

blogRecetas/templates/album/mostrarEntrada_.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Blog de Recetas</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album/">

    

    

<link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
  </head>
  <body>
    
<header>
  <!-- esta es la barra colapsada -->
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="/admin" class="text-white">Administrador</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'blog:inicioUsuario' %}" class="text-white">Mis Entradas</a></li>
            <li><a href="{% url 'blog:editarPerfil' %}" class="text-white">Editar Perfil ( {{ user.first_name }} {{ user.last_name }} )</a></li>
            {% endif %}
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!--esta es la barra sin colapsar -->
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'blog:inicio' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Recetas</strong>
      </a>      
      {% if not request.user.is_authenticated %}
      <a class="navbar-toggler" href="{% url 'blog:login' %}" style="align-self: right; align-items: right;position: absolute;top: 25%; left: 75%;">
        <strong>Login</strong>
      </a>
      {% endif %}
      {% if request.user.is_authenticated %}
      <a class="navbar-toggler" href="{% url 'blog:logout' %}?next={% url 'blog:inicio' %}" style="align-self: right; align-items: right;position: absolute;top: 25%; left: 75%;">
        <strong>Logout</strong>
      </a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>  
  </div>
</header>

<main>
  <!-- es la seccion central antes de las entradas -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">{{ entrada.titulo }}</h1>
        <p class="lead text-muted">{{ entrada.subtitulo }}</p>
        <!-- <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p> -->
      </div>
    </div>
  </section>

  <!-- aca van las entradas -->

  <div class="album py-5 bg-light">
    <a href="javascript:history.back()" class="btn btn-sm btn-outline-primary">Volver</a>
    <div class="container">
      {% if entrada.imagen %}
      <p><img src="{{ entrada.imagen.url }}" height="400px" width="600px"></p>
      {% endif %}      
      <p> {{ entrada.cuerpo|safe }} </p>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- debe ir un for para mostrar las entradas. Llegan por parametro como 'entradas'-->                
      </div>
      <hr>
      <small>Fecha: {{ entrada.fecha }}</small><br>
      <small>Autor: {{ entrada.autor }} |  Likes: {{ entrada.totalLikes }}</small>
      <hr>
      <div class="btn-group">                       
        {% if entrada.autor == request.user %}
          <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:editarEntrada' entrada.id %}">Edit</a>
          <a type="button" class="btn btn-sm btn-outline-danger" href="{% url 'blog:eliminarEntrada' entrada.id %}">Delete</a>                   
        {% endif %}
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:megusta' entrada.id %}">Me Gusta</a>
      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-0"><a href="/">Visit the homepage</a> or read our <a href="">getting started guide</a>.</p>
  </div>
</footer>


    <script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>