blog/urls.py
from django.urls import path, include
from blog.views import *
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('', inicio, name='inicio'),
    path('inicio', inicio, name='inicio'),
    path('pages', mostrarEntradas, name='pages'),
    path('login', loginRequest, name='login'),
    path('entrada/<entr_id>',mostrarEntrada, name='mostrarEntrada'),
    path('inicioUsuario', mostrarEntradasUsuario, name='inicioUsuario'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('registro', registrarUsuario, name='registrarUsuario'),
    path('editarperfil', editarPerfil, name='editarPerfil'),
    path('nuevaEntrada', nuevaEntrada, name='nuevaEntrada'),
    path('editarEntrada/<entr_id>', editarEntrada, name='editarEntrada'),
    path('eliminarEntrada/<entr_id>', eliminarEntrada, name='eliminarEntrada'),
    path('megusta/<entr_id>', likeEntrada, name='megusta'),   
    path('favoritos', entradasFavoritas, name='favoritos'),
    path('about', about, name='about') ,
]

blogRecetas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('blog.urls','blog'),namespace='blog')),
    path('mensajeria/', include(('mensajeria.urls', 'mensajeria'), namespace='mensajeria')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mensajeria/urls.py
from unicodedata import name
from django.urls import path
from mensajeria.views import *


urlpatterns = [
    path('nuevoMensaje', nuevoMensaje, name='nuevoMensaje'),
    path('bandejaEntrada', bandejaEntrada, name='bandejaEntrada'),
    path('eliminarMensaje/<id>', eliminarMensaje, name='eliminarMensaje'),
    path('responderMensaje/<id>', responderMensaje, name='responderMensaje'),
    path('mostrarMensaje/<id>', mostrarMensaje, name='mostrarMensaje'),
]

mensajeria/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


class Mensaje(models.Model):
    # - Emisor
    emisor = models.ForeignKey(User, on_delete=models.CASCADE)
    # - Remitente
    remitente = models.ForeignKey(User, on_delete=models.CASCADE, related_name='remitente')
    # - Asunto
    asunto = models.CharField(max_length=50, default='')
    # - Cuerpo
    cuerpo = RichTextField()
    # - Leido
    leido = models.BooleanField(default=False)

mensajeria/forms.py
from tkinter import N
from tkinter.tix import Tree
from django.forms import ModelForm, ModelChoiceField
from ckeditor.widgets import CKEditorWidget
from mensajeria.models import Mensaje
from django.contrib.auth.models import User
from django import forms


class MensajeForm(ModelForm):
    class Meta:
        model = Mensaje
        fields = ['remitente', 'asunto', 'cuerpo']
    def __init__(self, *args, **kwargs):
        super(MensajeForm, self).__init__(*args, **kwargs)
        # self.fields['remitente']=ModelChoiceField(queryset=User.objects.all())
        self.fields['remitente'].label='Para:'

mensajeria/views.py
from contextlib import redirect_stderr
from urllib import request
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from mensajeria.forms import MensajeForm
from django.contrib import messages
from mensajeria.models import Mensaje
from django.db.models import Q


@login_required
def nuevoMensaje(request):
    ''' se crea y envía un nuevo mensaje (usuario debe estar logueado) '''        
    if request.method == 'POST':
        form = MensajeForm(request.POST)
        if(form.is_valid()):
            msg = form.save(commit=False)
            msg.emisor=request.user
            msg.save()
            messages.success(request, "Se envió el mensaje")
            return redirect('mensajeria:bandejaEntrada')
        else:
            messages.error(request, "El mensaje no se pudo enviar correctamente")
            return redirect('mensajeria:bandejaEntrada')
    else:        
        form = MensajeForm()
        return render(request, 'mensajeria/nuevoMensaje.html', {"form":form})


@login_required
def eliminarMensaje(request, id):
    ''' se elimina un mensaje de la bandeja de mensajes de un usuario logueado '''
    mensaje = Mensaje.objects.get(id=id)
    if request.method == 'POST':
        mensaje = Mensaje.objects.get(id=id)
        mensaje.delete()
        messages.success(request, "Se elimino el mensaje")
        return redirect('mensajeria:bandejaEntrada')
    else:
        return render(request, 'mensajeria/confirmarBorrado.html', {'mensaje':mensaje})


@login_required
def mostrarMensaje(request, id):
    ''' se muestra un mensaje y se marca como leído '''
    mensaje = Mensaje.objects.get(id=id)
    if request.user == mensaje.remitente:
        mensaje.leido=True
        mensaje.save()    
    return render(request, 'mensajeria/mostrarMensaje.html', {'mensaje':mensaje})


@login_required
def responderMensaje(request, id):
    ''' se responde a un mensaje en la bandeja de mensajes de un usuario logueado '''
    mensaje = Mensaje.objects.get(id=id)
    if request.method == "POST":
        form = MensajeForm(request.POST)
        if(form.is_valid()):
            form.save()
            redirect('mensajeria:bandejaEntrada')
        else:
            messages.error("Hubo un error, no se pudo responder el mensaje")
            redirect('mensajeria:mostrarMensaje', id)
    else:
        asunto = 'Re: '+mensaje.asunto
        form = MensajeForm(initial={'emisor':mensaje.remitente,'remitente':mensaje.emisor, 'cuerpo':mensaje.cuerpo,'asunto':asunto})
    return render(request, 'mensajeria/nuevoMensaje.html', {'form':form})


@login_required
def bandejaEntrada(request):
    ''' se muestra la bandeja de entrada del usuario logueado '''
    mensajes = Mensaje.objects.filter(Q(emisor=request.user) | Q(remitente=request.user))
    return render(request, 'mensajeria/bandejaEntrada.html', {"mensajes":mensajes})

blogRecetas/templates/mensajeria/bandejaEntrada.html
{% extends 'album/index.html' %}
{% load static %}

{% block seccionCentral %}
<h1 class="fw-light">Bandeja de Entrada</h1>
    <p>
        <a href="{% url 'mensajeria:nuevoMensaje' %}" class="btn btn-primary my-2">Nuevo Mensaje</a>
    </p>
{% endblock %}

{% block entradasBlock %}    
    <div class="shadow p-4 mb-5 bg-body rounded">
        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">De</th>
                <th scope="col">Para</th>
                <th scope="col">Asunto</th>
                </tr>
            </thead>            
            <tbody>
                {% for mensaje in mensajes %}
                
                <tr href="{% url 'mensajeria:mostrarMensaje' mensaje.id %}"><a href="{% url 'mensajeria:mostrarMensaje' mensaje.id %}">
                <th scope="row">{{ mensaje.id }}</th>
                <td>{{ mensaje.emisor }}</td>
                <td>{{ mensaje.remitente }}</td>
                <td>{{ mensaje.asunto }}</td>
                <td><a type="button" class="btn btn-sm btn-outline-danger" href="{% url 'mensajeria:eliminarMensaje' mensaje.id %}">Borrar</a>
                    <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'mensajeria:mostrarMensaje' mensaje.id %}">Ver</a>
                </td>              
                </a>
                </tr>                        
                {% endfor %}
            </tbody>            
            </table>
    </div>
    {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>              
        {% endfor %}
    {% endif %}
{% endblock %}

blogRecetas/templates/mensajeria/confirmarBorrado.html
{% extends 'album/index.html' %}
{% load static %}

{% block seccionCentral %}
<p class="lead text-muted">Está seguro que desea eliminar el mensaje: {{ mensaje.titulo }}</p>
<a href="javascript:history.back()" class="btn btn-secondary my-2">Cancelar</a>
<form action="{% url 'mensajeria:eliminarMensaje' mensaje.id %}" method="post"> {% csrf_token %}
    <button type="submit" class="btn btn-danger my-2">Borrar</a>
</form>

{% endblock %}

{% block entradasBlock %}    
{% endblock %}

blogRecetas/templates/mensajeria/mostrarMensaje.html
{% extends 'album/index.html' %}
{% load static %}

{% block seccionCentral %}
<h1 class="fw-light"></h1>
{% endblock %}

{% block entradasBlock %}
    <div>
        <a href="javascript:history.back()" class="btn btn-sm btn-outline-primary">Volver</a>
    <h5>De: {{mensaje.emisor}}</h5>
    <h5>Para: {{mensaje.remitente}}</h5>
        <div>
            <h5><small class="text-muted">Asunto: {{mensaje.asunto}}</small></h5>
        </div>
        <hr>
        <div>
            <p>
                {{mensaje.cuerpo|safe}}
            </p>
        </div>
        <hr>
        <strong>
            Visto: {% if mensaje.leido %} Si {% else %} No {% endif %}
        </strong>
    </div>
    {% if mensaje.emisor != request.user %}
    <a href="{% url 'mensajeria:responderMensaje' mensaje.id %}" class="btn btn-primary">Responder</a>
    {% endif %}
    {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>           
        {% endfor %}
    {% endif %}
{% endblock %}

blogRecetas/templates/mensajeria/nuevoMensaje.html
{% extends 'album/index.html' %}
{% load static %}

{% block seccionCentral %}
<h1 class="fw-light">Nuevo Mensaje</h1>
{% endblock %}

{% block entradasBlock %}
    {% if form %}
    <div class="shadow p-4 mb-5 bg-body rounded">
        <a href="javascript:history.back()" class="btn btn-sm btn-outline-primary">Volver</a>
    <form action="{% url 'mensajeria:nuevoMensaje' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
    </div>
    {% endif %}
    {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>           
        {% endfor %}
    {% endif %}
{% endblock %}